### ISSUE TITLE
缺少文档上所描述的那些辅助函数-defineMockData

### ISSUE THREAD

**Issue by itmanyong** [pengzhanbo/rspack-plugin-mock#2]
- 没有找到defineMockData的实现，但是vite-plugin版本是有的
- mock目录下的文件不能使用rsbuild的别名配置，vite版本可以

**Comment by pengzhanbo** [comment]
1. 由于在 rspack 这一侧，mock 文件的编译构建完全使用了 rspack 本身的能力，分开编译的开销 比 esbuild  要大些，反而合并编译的开销更小，因此在 rspack 这一侧，所有的 mock 文件都可以认为是在同一个 作用域中，不会像 vite 侧那样由于分开编译带来的问题。 因此 `defineMockData` 已经没有必要了。 不过考虑到 如果想从 `vite` 迁移到 `rspack` ，那么在 rspack  这一侧重新实现 `defineMockData` 也是有价值的。 因此我会在下个版本中 重新添加它。

2. 这是一个 bug ，由于我在插件内部判断 模块是否属于第三方依赖 的逻辑上出现了与 alias 的配置冲突的部分，导致 `alias` 配置的 模块前缀被 识别为了 第三方依赖。同样会在下个版本中修复。
