### ISSUE TITLE
rsbuild插件options.prefix不生效

### ISSUE THREAD

**Issue by itmanyong** [pengzhanbo/rspack-plugin-mock#4]
1.rsbuild插件options.prefix不生效,不会拦截代码内的请求,如下图配置
![image](https://github.com/user-attachments/assets/19ebb358-58fd-494d-92b3-b75fe4029f0c)

2.希望新增插件配置开关,用以控制是否读取proxy配置,有些情况下既有proxy配置代理到服务器,某些接口代理mock

3.请求的地址如果是域名或ip,非localhost的情况下,mock不会拦截这些请求,如下示例就不会被代理,即使配置了proxy
http://192.168.5.205:9898 -> proxy配置了无效

**Comment by pengzhanbo** [comment]
1. 已修复，等待版本更新

2. 可以通过 [mockOptions.enable](https://github.com/pengzhanbo/rspack-plugin-mock#optionsenabled) 关闭单个接口模拟。或者通过 [createDefineMock](https://github.com/pengzhanbo/rspack-plugin-mock#createdefinemocktransformer) 创建批量预处理mock 的 transformer。
   插件是围绕 `server.proxy` 进行设计的，`prefix` 仅是作为补充。关闭 `server.proxy` 属于本末倒置了。

3. mock 都是注入到 rspack-server 或 rsbuild-server 中的，无论是 localhost 或 IP 都会通过 mock 中间件。我在本地测试了 localhost 和 IP 访问，mock 均正常。
