### ISSUE TITLE
[bug]Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.

### ISSUE THREAD

**Issue by Rika-L** [pengzhanbo/rspack-plugin-mock#5]
会报这个但不影响使用
![image](https://github.com/user-attachments/assets/968b3f1f-5b81-453b-9247-288a1419510b)

以下是最小复现

```ts
import { defineConfig } from '@rsbuild/core';
import { pluginReact } from '@rsbuild/plugin-react';
import { pluginMockServer } from 'rspack-plugin-mock/rsbuild';

export default defineConfig({
  plugins: [pluginReact(),pluginMockServer()],
});

```

**Comment by pengzhanbo** [comment]
这个警告是由于你在一个非 esm 的项目中，在 .js 文件中使用了 esm 的语法。 你按照警告给你的建议进行修复即可。

**Comment by Rika-L** [comment]
> 这个警告是由于你在一个非 esm 的项目中，在 .js 文件中使用了 esm 的语法。 你按照警告给你的建议进行修复即可。

package.json中的type已经是module了

**Comment by pengzhanbo** [comment]
这个警告跟插件是无关的，插件包导出了 commonJS 和 esm 两种格式，同时支持 在 commonJS 和 esm 项目中使用。

你得看看你运行 npm scripts 所在的工作目录 （cwd） 下的 `package.json` 中是否有正确的 `type` 字段。

**Comment by Rika-L** [comment]
> 这个警告跟插件是无关的，插件包导出了 commonJS 和 esm 两种格式，同时支持 在 commonJS 和 esm 项目中使用。
> 
> 你得看看你运行 npm scripts 所在的工作目录 （cwd） 下的 `package.json` 中是否有正确的 `type` 字段。

谢谢，我使用nvm把node从22改到20则不存在此问题
